### ISSUE TITLE
Can't scroll fully down in the drop-down

### ISSUE THREAD

**Issue by Tejas2805** [nus-cs2103-AY2021S1/website#3]
Can't scroll down in the drop-down to see the hidden items in it.

![Screen Shot 2020-08-28 at 7 31 18 AM](https://user-images.githubusercontent.com/35946746/91504775-a96d3600-e900-11ea-9d03-ccdc6ccf6bcf.png)

**Comment by damithc** [comment]
Thanks for the bug report @Tejas2805 
This is a limitation of the platform used. I've split the dropdown menu into two as a workaround.
