### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by aizatazhar** [nus-cs2103-AY2021S1/website#6]
In [tp expectations](https://github.com/nus-cs2103-AY2021S1/website/blob/master/admin/tp-expectations.md) `does it make the the user's life easier` has duplicated `the`s

in [tp supervision](https://github.com/nus-cs2103-AY2021S1/website/blob/master/admin/tp-supervision.md) `It is up to you to get as much feedback from the as you need` should be `It is up to you to get as much feedback from them as you need`

In [Week 7 project](https://nus-cs2103-ay2021s1.github.io/website/schedule/week7/project.html), `start implementing the next version` should have `start` capitalised. I think the relevant code is [here](https://github.com/nus-cs2103-AY2021S1/website/blob/master/admin/tp-tasks.mbdf)

**Comment by damithc** [comment]
Thanks again @aizatazhar Will be fixed in the next update.
Let us know if you spot any more.
