### ISSUE TITLE
Broken AB3 link

### ISSUE THREAD

**Issue by aizatazhar** [nus-cs2103-AY2021S1/website#7]
Under the website's Project Links, the link to AB3 points to [https://github.com/nus-cs2103-AY2021S1/addressbook-level3](https://github.com/nus-cs2103-AY2021S1/addressbook-level3).

I believe the relevant code can be found [here](https://github.com/nus-cs2103-AY2021S1/website/blob/master/_markbind/headers/header.md)

**Comment by damithc** [comment]
Thanks for the bug report @aizatazhar Much appreciated. Will be fixed in the next update.
