### ISSUE TITLE
[W9.3b] Typo

### ISSUE THREAD

**Issue by wakululuu** [nus-cs2103-AY2021S1/website#8]
Extra "n" after "using sequence diagrams" in the pop-up information activated by hovering over "a similar technique"

<img width="783" alt="Screenshot 2020-12-01 at 3 31 33 PM" src="https://user-images.githubusercontent.com/28750239/100710179-4cdf5280-33ea-11eb-9aee-d45627c34576.png">

**Comment by damithc** [comment]
Thanks for the bug report @wakululuu
Will fix in the next semester's edition of the book.
