### ISSUE TITLE
[W10.1c] Typo

### ISSUE THREAD

**Issue by wakululuu** [nus-cs2103-AY2021S1/website#9]
Perhaps the highlighted portion should be "A certain class" or "Certain classes"

<img width="817" alt="Screenshot 2020-12-01 at 4 24 32 PM" src="https://user-images.githubusercontent.com/28750239/100715179-c595dd00-33f1-11eb-9a91-8fbc3415dd74.png">

**Comment by damithc** [comment]
Thanks for the bug report @wakululuu 
Will fix in the next semester's edition of the book.
